name: SonarQube Cloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Paso 2: Limpiar el caché de Gradle
      - name: Clean Gradle Cache
        run: rm -rf ~/.gradle

      # Paso 3: Configurar JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      # Paso 4: Construir el proyecto con dependencias actualizadas y aceptar términos
      - name: Build the project with refreshed dependencies and accepted terms
        run: ./gradlew clean build --refresh-dependencies --scan -Dgradle.buildScan.termsOfService=true --info

      # Paso 5: Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # Paso 6: Construir y analizar con SonarCloud
      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -Dscan=false --info --stacktrace

      # Paso 7: Crear una imagen Docker sin depender de docker.elastic.co
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg BASE_IMAGE=alpine:latest \ # Usando una imagen pública como base
            -t my-docker-image .
