name: SonarQube Cloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Initial Disk Space
        run: df -h

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Aggressively Clean Gradle Cache
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.gradle/wrapper/

      - name: Prune Docker System
        run: docker system prune -af

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build the project (skip Docker tasks)
        run: |
          ./gradlew clean build \
            -x distribution:docker:buildWolfiDockerImage \
            -x distribution:docker:buildCloudEssDockerImage \
            -x distribution:docker:buildUbiDockerImage \
            --quiet

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -Dscan=false --quiet

      - name: Check Final Disk Space
        run: df -h
